# Setup
title:        PJM Queue Changes Tracker
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/jekyll-cayman-theme-master/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Author name
  url:        https://briankusiak.github.io/torchcleanenergy/jekyll-cayman-theme-master/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown